#!/usr/bin/env python3

import sys
import glob
from importlib import import_module
from Commands.command import Command

from os.path import dirname, basename, isfile, join
import glob


# arguments provided to cely-local.
args = sys.argv[1:]
list = []
blnFound = False

modules = glob.glob(join(dirname(__file__)+"/Commands", "*.py"))
__all__ = [ basename(f)[:-3] for f in modules if isfile(f) and not f.endswith('__init__.py') and not f.endswith('command.py')]

# loop though every commmand in the Commands directory.
for mod in __all__:
    myClass = import_module("Commands." + mod).Module()
    strCommand = myClass.getCommand()
    list.append(myClass.getListItem())

    if (len(args) > 0 and strCommand == args[0]):
        blnFound = True
        myClass.handle(args[1:])
        break


if (blnFound == False):
    for item in list:
        strCommand = item["command"]
        strDescription = item["description"]

        print(strCommand.ljust(20) + strDescription)
